kind = "web"
previewPath = "/"
title = "Nyv0x SMP"
version = "1.0.0"
id = "artifacts/nyv0x-smp"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26224

[services.development]
run = "pnpm --filter @workspace/nyv0x-smp run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nyv0x-smp", "run", "build" ]
publicDir = "artifacts/nyv0x-smp/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26224"
BASE_PATH = "/"
